FROM crinabarbieru/wordpress-vulnerable:latest

COPY plugins/simple-basic-contact-form /var/www/html/wp-content/plugins/simple-basic-contact-form
COPY plugins/wp-stripe-donation /var/www/html/wp-content/plugins/wp-stripe-donation